server_list:
    path: /server/list
    controller: App\Controller\ServerController::listServers
server_location:
    path: /server/location
    controller: App\Controller\ServerController::listServerLocations